/* tslint:disable */
/* eslint-disable */
/**
 * ScanChain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  WalletInfo,
} from '../models';
import {
    WalletInfoFromJSON,
    WalletInfoToJSON,
} from '../models';

export interface GetWalletInfoEndpointRequest {
    address?: string;
}

/**
 *
 */
export class WalletApi extends runtime.BaseAPI {

    /**
     */
    async getWalletInfoEndpointRaw(requestParameters: GetWalletInfoEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletInfo>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['Address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/wallet/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletInfoFromJSON(jsonValue));
    }

    /**
     */
    async getWalletInfoEndpoint(requestParameters: GetWalletInfoEndpointRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletInfo> {
        const response = await this.getWalletInfoEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
