/* tslint:disable */
/* eslint-disable */
/**
 * ScanChain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WalletToken
 */
export interface WalletToken {
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'tokenAddress'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'symbol'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'logo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'thumbnail'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'decimals'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'balance'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof WalletToken
     */
    'possibleSpam'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WalletToken
     */
    'verifiedContract'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'totalSupply'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'totalSupplyFormatted'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'percentageRelativeToTotalSupply'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'securityScore'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WalletToken
     */
    'balanceFormatted'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'usdPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'usdPrice24hrPercentChange'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'usdPrice24hrUsdChange'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'usdValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'usdValue24hrUsdChange'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof WalletToken
     */
    'nativeToken'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof WalletToken
     */
    'portfolioPercentage'?: number;
}

