/* tslint:disable */
/* eslint-disable */
/**
 * ScanChain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WalletTransactionItem
 */
export interface WalletTransactionItem {
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'hash'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'nonce'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'transactionIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'fromAddressEntity'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'fromAddressEntityLogo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'fromAddress'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'fromAddressLabel'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'toAddressEntity'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'toAddressEntityLogo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'toAddress'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'toAddressLabel'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'value'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'gas'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'gasPrice'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'input'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'receiptCumulativeGasUsed'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'receiptGasUsed'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'receiptContractAddress'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'receiptRoot'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'receiptStatus'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'blockTimestamp'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'blockNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionItem
     */
    'blockHash'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof WalletTransactionItem
     */
    'transferIndex'?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactionItem
     */
    'transactionFee'?: number;
}

