/* tslint:disable */
/* eslint-disable */
/**
 * ScanChain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WalletTransactionItem } from './wallet-transaction-item';

/**
 * 
 * @export
 * @interface WalletTransactions
 */
export interface WalletTransactions {
    /**
     * 
     * @type {string}
     * @memberof WalletTransactions
     */
    'cursor'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactions
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof WalletTransactions
     */
    'page'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactions
     */
    'address'?: string | null;
    /**
     * 
     * @type {Array<WalletTransactionItem>}
     * @memberof WalletTransactions
     */
    'result'?: Array<WalletTransactionItem> | null;
}

