/* tslint:disable */
/* eslint-disable */
/**
 * ScanChain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface WalletToken
 */
export interface WalletToken {
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    tokenAddress?: string | null;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    symbol?: string | null;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    logo?: string | null;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    thumbnail?: string | null;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    decimals?: number;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    balance?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof WalletToken
     */
    possibleSpam?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof WalletToken
     */
    verifiedContract?: boolean;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    totalSupply?: string | null;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    totalSupplyFormatted?: string | null;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    percentageRelativeToTotalSupply?: number | null;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    securityScore?: number | null;
    /**
     *
     * @type {string}
     * @memberof WalletToken
     */
    balanceFormatted?: string | null;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    usdPrice?: number;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    usdPrice24hrPercentChange?: number;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    usdPrice24hrUsdChange?: number;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    usdValue?: number;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    usdValue24hrUsdChange?: number;
    /**
     *
     * @type {boolean}
     * @memberof WalletToken
     */
    nativeToken?: boolean;
    /**
     *
     * @type {number}
     * @memberof WalletToken
     */
    portfolioPercentage?: number;
}

/**
 * Check if a given object implements the WalletToken interface.
 */
export function instanceOfWalletToken(value: object): value is WalletToken {
    return true;
}

export function WalletTokenFromJSON(json: any): WalletToken {
    return WalletTokenFromJSONTyped(json, false);
}

export function WalletTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletToken {
    if (json == null) {
        return json;
    }
    return {

        'tokenAddress': json['tokenAddress'] == null ? undefined : json['tokenAddress'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'name': json['name'] == null ? undefined : json['name'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'thumbnail': json['thumbnail'] == null ? undefined : json['thumbnail'],
        'decimals': json['decimals'] == null ? undefined : json['decimals'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'possibleSpam': json['possibleSpam'] == null ? undefined : json['possibleSpam'],
        'verifiedContract': json['verifiedContract'] == null ? undefined : json['verifiedContract'],
        'totalSupply': json['totalSupply'] == null ? undefined : json['totalSupply'],
        'totalSupplyFormatted': json['totalSupplyFormatted'] == null ? undefined : json['totalSupplyFormatted'],
        'percentageRelativeToTotalSupply': json['percentageRelativeToTotalSupply'] == null ? undefined : json['percentageRelativeToTotalSupply'],
        'securityScore': json['securityScore'] == null ? undefined : json['securityScore'],
        'balanceFormatted': json['balanceFormatted'] == null ? undefined : json['balanceFormatted'],
        'usdPrice': json['usdPrice'] == null ? undefined : json['usdPrice'],
        'usdPrice24hrPercentChange': json['usdPrice24hrPercentChange'] == null ? undefined : json['usdPrice24hrPercentChange'],
        'usdPrice24hrUsdChange': json['usdPrice24hrUsdChange'] == null ? undefined : json['usdPrice24hrUsdChange'],
        'usdValue': json['usdValue'] == null ? undefined : json['usdValue'],
        'usdValue24hrUsdChange': json['usdValue24hrUsdChange'] == null ? undefined : json['usdValue24hrUsdChange'],
        'nativeToken': json['nativeToken'] == null ? undefined : json['nativeToken'],
        'portfolioPercentage': json['portfolioPercentage'] == null ? undefined : json['portfolioPercentage'],
    };
}

export function WalletTokenToJSON(json: any): WalletToken {
    return WalletTokenToJSONTyped(json, false);
}

export function WalletTokenToJSONTyped(value?: WalletToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'tokenAddress': value['tokenAddress'],
        'symbol': value['symbol'],
        'name': value['name'],
        'logo': value['logo'],
        'thumbnail': value['thumbnail'],
        'decimals': value['decimals'],
        'balance': value['balance'],
        'possibleSpam': value['possibleSpam'],
        'verifiedContract': value['verifiedContract'],
        'totalSupply': value['totalSupply'],
        'totalSupplyFormatted': value['totalSupplyFormatted'],
        'percentageRelativeToTotalSupply': value['percentageRelativeToTotalSupply'],
        'securityScore': value['securityScore'],
        'balanceFormatted': value['balanceFormatted'],
        'usdPrice': value['usdPrice'],
        'usdPrice24hrPercentChange': value['usdPrice24hrPercentChange'],
        'usdPrice24hrUsdChange': value['usdPrice24hrUsdChange'],
        'usdValue': value['usdValue'],
        'usdValue24hrUsdChange': value['usdValue24hrUsdChange'],
        'nativeToken': value['nativeToken'],
        'portfolioPercentage': value['portfolioPercentage'],
    };
}

